/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_khopan_camera_Camera */

#ifndef _Included_com_khopan_camera_Camera
#define _Included_com_khopan_camera_Camera
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_khopan_camera_Camera
	 * Method:    capture
	 * Signature: ()[B
	 */
	JNIEXPORT jbyteArray JNICALL Java_com_khopan_camera_Camera_capture
	(JNIEnv*, jobject);

#ifdef __cplusplus
}
#endif
#endif
