/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_khopan_camera_CameraManager */

#ifndef _Included_com_khopan_camera_CameraManager
#define _Included_com_khopan_camera_CameraManager
#ifdef __cplusplus
extern "C" {
#endif
	/*
	 * Class:     com_khopan_camera_CameraManager
	 * Method:    getAllCameraDevices
	 * Signature: ()[Lcom/khopan/camera/Camera;
	 */
	JNIEXPORT jobjectArray JNICALL Java_com_khopan_camera_CameraManager_getAllCameraDevices
	(JNIEnv*, jclass);

#ifdef __cplusplus
}
#endif
#endif
